version: "3.8"

services:
  db:
    image: postgres:15
    container_name: beauty_server_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beauty_server_db
    ports:
      - "5228:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d beauty_server_db"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - beauty_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beauty_server_app
    environment:
      DATABASE_DSN: postgres://postgres:postgres@beauty_server_db:5432/beauty_server_db?sslmode=disable
      PORT: 8080
      DEFAULT_ORGANIZATION_COLOR: "#FFFFFF"
      TELEGRAM_2FA_SERVER: http://213.183.53.46:5002
      TELEGRAM_2FA_TOKEN: 80a0c3ad4de64ebeb753604fdbb455e8
    ports:
      - "8228:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - beauty_network
# Сделать чтобы запускался nginx с документацией
networks:
  beauty_network:
    driver: bridge