services:
  db:
    image: postgres:15
    container_name: beauty_server_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beauty_server_db
    ports:
      - "5228:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d beauty_server_db" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - beauty_network
  api:
    image: beauty-server
    build:
      context: .
      dockerfile: Api/Dockerfile
    container_name: beauty_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8228:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - beauty_network
    volumes:
      - ./appsettings.json:/app/appsettings.json

networks:
  beauty_network:
    driver: bridge