name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SERVER_IP }}

      - name: Adding Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Copy files to the server
        run: |
          rsync -avz --exclude=".git" --exclude=".github" --exclude="node_modules" ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:~/beauty_server

      - name: Build and Deploy on Server using Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd ~/beauty_server
            sudo docker-compose down || true
            sudo docker rmi beauty_server_app
            sudo docker-compose up -d --build
          EOF
