name: Deploy to Server via SSH

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t beauty-server .

      - name: Save Docker image
        run: |
          docker save beauty-server -o beauty-server.tar

      - name: Copy Docker image to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          source: "beauty-server"
          target: "/beauty_server/beauty-server.tar"

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          script: |
            cd /beauty_server
            docker load < beauty-server.tar
            docker stop beauty-server || true
            docker rm beauty-server || true
            docker run -d --name beauty-server -p 5228:8080 beauty-server
